### ISSUE TITLE
cannot import name 'ElectricalConnectionInstanceW'

### ISSUE THREAD

**Issue by clausagerskov** [openworm/CElegansNeuroML#104]
Running Windows 10 home edition, python 2.7

I have compiled sibernetic in windows and am trying to run the sibernetic_c302.py using python 2.7, but im running into trouble when the script tries to run c302.py from CElegansNeuroML. In the beginning it tries to import the class ElectricalConnectionInstanceW which doesnt exist (anymore?). Has this class been removed from neuroml?

**Comment by pgleeson** [comment]
@clausagerskov It looks like you might be using an old version of libNeuroML. Make sure you have the latest from the development branch on GitHub, or do a 'pip install libneuroml'. (I should really make a new release to master soon, but that generally happens with a new beta release of all nml libraries...)

**Comment by clausagerskov** [comment]
I talked to David Lung and he suggested just that, but then there is the problem of the development branch not having the realtime_output to the run_lems_with_jneuroml_neuron function which is in the master, which the sibernetic_302.py calls

**Comment by pgleeson** [comment]
Note there are 2 libraries, libNeuroML where you need the development branch, and pyNeuroML, where you need the master branch and that's where run_lems_with_jneuroml_neuron is found.

**Comment by clausagerskov** [comment]
Thats exactly the info i needed thanks! now i just need to find out where to get the nrnivmodl file for windows

**Comment by pgleeson** [comment]
Ok, glad it works now.
