### ISSUE TITLE
Can't get NEURON to open hoc file generated from PVDL morphology

### ISSUE THREAD

**Issue by slarson** [openworm/CElegansNeuroML#13]
This was reported by a contributor:

> I managed to make the network simulation work and I also generated NEURON files for the morphology from the NeuroML.  The problem I get is that neuron doesn’t seem to manage to open these hoc file for the PVDL neuron as it seems the procedure is too big for it to run… I am wondering if there’s a way around that.

**Comment by pgleeson** [comment]
Retested this with commit https://github.com/openworm/CElegansNeuroML/commit/00b02304e08d8343519d98f97477b58d401fe410 and now works
