### ISSUE TITLE
'No module named airspeed' when running test.sh under c302 first time

### ISSUE THREAD

**Issue by slarson** [openworm/CElegansNeuroML#14]
>unknown1040f3847b74:c302 slarson$ ./test.sh
>Traceback (most recent call last):
>  File "c302_A.py", line 1, in <module>
>    from c302 import generate
>  File "/Users/slarson/Documents/CElegansNeuroML/CElegans/pythonScripts/c302/c302.py", line 15, in <module>
>    import airspeed
>ImportError: No module named airspeed

Worse yet, when trying to install it, I got this:

>unknown1040f3847b74:c302 slarson$ pip install airspeed
>Downloading/unpacking airspeed
>  Could not find a version that satisfies the requirement airspeed (from versions: 0.2dev-20131105, 0.4.1dev-20131108, 0.4.2dev-20131111, 0.4dev-20131106)
>Cleaning up...
>No distributions matching the version for airspeed

According [to this](http://stackoverflow.com/questions/18230956/could-not-find-a-version-that-satisfies-the-requirement-pytz) the message "Could not find a version that satisfies the requirement airspeed" is:

>Starting with v1.4, pip will only install stable versions as specified by PEP426 by default.

I get that I can go ahead and install it using pip install airspeed --pre but maybe we shouldn't be using airspeed if there won't be a good way to auto install it?  How important is it?

**Comment by pgleeson** [comment]
Better instructions for installing c302 have been added here: https://github.com/openworm/CElegansNeuroML/tree/master/CElegans/pythonScripts/c302#to-install--test
