### ISSUE TITLE
Replace the _GJ .nml files with an "innexin" model

### ISSUE THREAD

**Issue by slarson** [openworm/CElegansNeuroML#18]
The _GJ generated .nml files are present in the generatedNeuroML2 directory.  Worse, they don't have implementations so the dynamics make no sense.  We should replace them all with some kind of "innexin".  This also means modifying celegans.net.xml

- [ ] Modify celegans.net.xml anywhere there is a reference to some _GJ "synapse", change to "innexin"
- [ ] Identify a NeuroML gap junction model with actual dynamics that we can use for the time being as a "mock innexin"
- [ ] Create an "innexin.nml" and use the gap junction model for its contents
- [ ] test by running c302 with cells connected by innexins that dynamics actually appear.

@pgleeson -- is there a better way than modifying the files directly at this point?  Should we instead modify some script that creates the file -- I have lost track if RegenerateConnectome.py does this.

**Comment by pgleeson** [comment]
The cleanups in #20 have resolved this. There is now only one _GJ.nml file in the generated nml2 files, [Generic_GJ.nml](https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/generatedNeuroML2/Generic_GJ.nml), which is used for all gap junction connections in [CElegans.net.nml](https://raw.githubusercontent.com/openworm/CElegansNeuroML/master/CElegans/generatedNeuroML2/CElegans.net.nml).
