### ISSUE TITLE
Clean up/check neuroConstruct project & generated NeuroML files

### ISSUE THREAD

**Issue by pgleeson** [openworm/CElegansNeuroML#20]
The CElegans neuroConstruct project and the files generated from this in [generatedNeuroML](https://github.com/openworm/CElegansNeuroML/tree/master/CElegans/generatedNeuroML) and [generatedNeuroML2](https://github.com/openworm/CElegansNeuroML/tree/master/CElegans/generatedNeuroML2) predate all of the more recent work with [c302](https://github.com/openworm/CElegansNeuroML/tree/master/CElegans/pythonScripts/c302) and the [muscle cell model](https://github.com/openworm/muscle_model/tree/master/NeuroML2) and also recent updates to NeuroML 2 (e.g. [gap junctions](https://github.com/LEMS/jLEMS/issues/31)).

Working to update this to make updates from these other models easier to incorporate.

**Comment by travs** [comment]
How extensively do you think we should be rearranging things? Does this issue need its own milestone potentially?

**Comment by pgleeson** [comment]
The neuroConstruct files have been cleaned up/retested and new issues should be opened when there are new tasks related to this (e.g. importing c302 generated nets into nC)
