### ISSUE TITLE
Change the path for c302tuner.py

### ISSUE THREAD

**Issue by VahidGh** [openworm/CElegansNeuroML#24]
Trying to double check [this code](https://github.com/openworm/CElegansNeuroML/blob/a76039fd1b3bccd9c613524730731fff067e27af/CElegans/pythonScripts/c302/tune/c302tuner.py) ...
I guess the path for this script should be changed :)

    if not os.path.isfile('c302.py'):
        print('This script should be run from dir: CElegansNeuroML/CElegans/pythonScripts/c302')
        exit()

**Comment by pgleeson** [comment]
Yes, that file should be run one directory up with 

    python tune/c302tuner.py

As mentioned that's still in development. Plenty more to be done there...

**Comment by pgleeson** [comment]
Some good progress here... 

    python tune/c302tuner.py -opt

will run neurotune (my forks of neurotune & pyelectro...) using pyNeuroML and tune the NeuroML2 model, changing only leak_cond_density, k_slow_cond_density, k_fast_cond_density, ca_boyle_cond_density & specific_capacitance and try to match the [experimental data](https://github.com/openworm/muscle_model/blob/master/pyramidal_implementation/W05042200_1_1_3_1.txt.png) @vellamike was tuning against.

Mike's results:

![mike's results](https://raw.githubusercontent.com/openworm/muscle_model/master/pyramidal_implementation/overlay1.png)

Current tuned version here:

![figure_1](https://cloud.githubusercontent.com/assets/1556687/6693099/a802625e-ccc8-11e4-99a0-ffa2f44c2240.png)


Plenty more to do...

**Comment by VahidGh** [comment]
@pgleeson, thanks for your attention :)
Updated repos, but my output was a little different!

![image](https://cloud.githubusercontent.com/assets/6655104/6695160/4a31995c-ccf4-11e4-8566-f32f35d521ff.png)

Would you please shed more light on my way by answering these questions:
1. How do we decide on which values to choose for min-max constrains and weights?
2. What is the fitness function based on?

Also, when trying to run [example 2](https://github.com/pgleeson/neurotune/blob/master/examples/example_2/optimization.py) of the Neurotune, getting this error:
```
Traceback (most recent call last):
  File "/home/vahid/git/neurotune/examples/example_2/optimization.py", line 297, in <module>
    surrogate_t, surrogate_v = controller.run_individual(sim_var,show=False)
  File "/home/vahid/git/neurotune/examples/example_2/optimization.py", line 155, in run_individual
    axon.insert('na')
ValueError: argument not a density mechanism name.
```
