### ISSUE TITLE
Question on simulations

### ISSUE THREAD

**Issue by CliffracerX** [openworm/CElegansNeuroML#26]
What brought me here was the video of the simulated brain controlling the Lego robot, found out about it while reading about general AI stuff.

How would one go about setting up something like that?  Is it a fairly complicated process, or could I set it up in something like Unity3d, even potentially dusting off my old Mindstorms set and trying to set the thing up on that?

**Comment by pgleeson** [comment]
@CliffracerX, you should find some information related to that on http://www.connectomeengine.com

**Comment by CliffracerX** [comment]
I grabbed the GoPiGo code, as I'm imagining that it could have stuff that may be of use to me.  Good thing I took a Python class recently!  :p

**Comment by CliffracerX** [comment]
Well, I got it working using the help of IronPython, seems to work fine for the most part, with the exception of the food sensors.  Getting a direct view of the food from a specific distance seems to shut off all neural activity until the food is removed from sight.  Any idea why it might be doing that?  Should I post some code or videos?

**Comment by pgleeson** [comment]
Best person to talk to about this is probably Tim Busbice at the Connectome Engine. He should be able to help you.
