### ISSUE TITLE
Make OpenSourceBrain's visualization of this repo include Hive Plots

### ISSUE THREAD

**Issue by slarson** [openworm/CElegansNeuroML#57]
This should tie together some recent issues that have come up.  Based on what @tarelli said (openworm/org.geppetto.docs#32) on the idea of using the widgets:

> Geppetto is meant to be a platform integrated with data/model repos rather than covering the full life cycle

it occurs to me that in order to make it easy to have Geppetto's hive plots (openworm/OpenWorm#89) be accessible to all, that we should try to go through [OpenSourceBrain's view of this repo](http://www.opensourcebrain.org/projects/celegans), which reuses Geppetto behind the scenes.

So the question for this task is, what modifications do we need to make to this repo so that when we go to [visualize the network](http://www.opensourcebrain.org/projects/celegans?explorer=https%3A%2F%2Fraw.githubusercontent.com%2Fopenworm%2FCElegansNeuroML%2Fmaster%2FCElegans%2FgeneratedNeuroML2%2FCElegans.net.nml) (which by the way doesn't seem to be working right now? cc:@pgleeson ) we get the lovely [connectivity widget](docs.geppetto.org/en/latest/connectivityW.html) set up by default?

And the answer to this possibly can get included in improvements to the Geppetto docs (openworm/org.geppetto.docs#32) to boot.

cc: @borismarin @gidili

**Comment by borismarin** [comment]
I would do that for the default c302 project in live.geppetto.org as well. @slarson we can also leverage the ButtonBarWidget(TM) to pop up the hive plot - by default, every model loaded via OSB has a button for the displaying the connectivity (matrix "mode").

**Comment by slarson** [comment]
Sweet!  @borismarin  Do you have a good sense for how we could break down the task into discrete actions?

**Comment by borismarin** [comment]
@slarson quick brainstorming here, then we can open concrete cards:
- [] decide the best way to include qualitative information (e.g. which neurons are "sensory", which are "interneurons"...) into the NeuroML2 model (this can already be done via annotations, which can contain pretty much anything), but I don't think text parsing is the best way of solving this problem (@tarelli, @adrianq, any thoughts on that?). Another interim solution is hardcoding  CellName->category maps into the geppetto script, which also seems abominable to me.
- [] add a [button bar widget](http://docs.geppetto.org/en/latest/bubarW.html) to the [c302 live.geppetto.org sample(https://live.geppetto.org/geppetto?load_project_from_id=6) which fires up a connectivity widget in hive mode, using the categories described above.

**Comment by tarelli** [comment]
[This](https://github.com/openworm/org.geppetto.core/tree/master/src/main/resources/projects/C302) is where c302 comes from in live.geppetto.core. script.js and script2.js are the two files where to add the chord plot. Note that now we have an experiment where all cells have been recorded :)

**Comment by tarelli** [comment]
@borismarin I think it's a question for NeuroML as anything that doesn't come from the NML file itself will be an hack. And as for NeuroML using the annotations that would also be an hack. What's the process to propose/contribute something like this? cc pgleeson

**Comment by pgleeson** [comment]
There could be some "standard" annotations in the NeuroML which could be interpreted in some convenient way by Geppetto, until we settle on an "official" set of annotations. Some already used are:

    <property tag="numberInternalDivisions" value="3"/>  (in a segmentGroup for nseg)

    <property tag="color" value="0.796875 0.0 0.19921875"/> (in a population for color)

A quick and dirty solution here would be to add something like:

    <property tag="type" value="sensory"/> 

to the populations. The connectivity widget can offer an option to group by "type" iff it finds the tag there... While this is ad hoc, it is portable to other models: some pops of the same type ("excitatory") might be useful to group under some conditions...

**Comment by pgleeson** [comment]
Latest committed nets for c302 include colours for different cell types, which propagate through to the connectivity widgets incl. hive plot:

![selection_590](https://user-images.githubusercontent.com/1556687/36204966-febd7d3c-1184-11e8-9a9c-7baca3d2acda.png)

**Comment by pgleeson** [comment]
Closing this & more specific issues can be opened based on (limitations in) current OSB functionality
