### ISSUE TITLE
conn_number_override issue - AttributeError GradedSynapse.gbase

### ISSUE THREAD

**Issue by lungd** [openworm/CElegansNeuroML#73]
Hi guys,

I am working on the tap withdrawal circuit which overrides some connections (conn_number_override).
The problem is that the synapses can be of type GradedSynapse so there is no syn0.gbase at line:
https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/c302/c302.py#L690

But there is a syn0.conductance so I guess there should be a isinstance() check?

Best,
David

**Comment by pgleeson** [comment]
Hi @lungd, good catch, I hadn't tested conn_number_override with the more recent parameter sets. This should be fixed in the [latest commit](https://github.com/openworm/CElegansNeuroML/commit/8c3b6f151f32b98dca421d45553db1cead34bbaa).
